// <auto-generated />
using System;
using Cite.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cite.Api.Migrations.PostgreSQL.Migrations
{
    [DbContext(typeof(CiteContext))]
    [Migration("20251002200651_system_role_fix")]
    partial class system_role_fix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cite.Api.Data.Models.ActionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("ActionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("action_number");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modified");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluation_id");

                    b.Property<int>("InjectNumber")
                        .HasColumnType("integer")
                        .HasColumnName("inject_number");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_checked");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<int>("MoveNumber")
                        .HasColumnType("integer")
                        .HasColumnName("move_number");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("TeamId");

                    b.ToTable("actions");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.DutyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modified");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluation_id");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("TeamId");

                    b.ToTable("duties");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.DutyUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("DutyId")
                        .HasColumnType("uuid")
                        .HasColumnName("duty_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DutyId");

                    b.HasIndex("UserId", "DutyId")
                        .IsUnique();

                    b.ToTable("duty_users");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.EvaluationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrentMoveNumber")
                        .HasColumnType("integer")
                        .HasColumnName("current_move_number");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modified");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("GalleryExhibitId")
                        .HasColumnType("uuid")
                        .HasColumnName("gallery_exhibit_id");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("ScoringModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("scoring_model_id");

                    b.Property<string>("SituationDescription")
                        .HasColumnType("text")
                        .HasColumnName("situation_description");

                    b.Property<DateTime>("SituationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("situation_time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ScoringModelId");

                    b.ToTable("evaluations");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.EvaluationMembershipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluation_id");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("f870d8ee-7332-4f7f-8ee0-63bd07cfd7e6"))
                        .HasColumnName("role_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("EvaluationId", "UserId", "GroupId")
                        .IsUnique();

                    b.ToTable("evaluation_memberships");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.EvaluationRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("AllPermissions")
                        .HasColumnType("boolean")
                        .HasColumnName("all_permissions");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int[]>("Permissions")
                        .HasColumnType("integer[]")
                        .HasColumnName("permissions");

                    b.HasKey("Id");

                    b.ToTable("evaluation_roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a3f26cd-9d99-4b98-b914-12931e78619a"),
                            AllPermissions = true,
                            Description = "Can perform all actions on the Evaluation in administration",
                            Name = "Owner",
                            Permissions = new int[0]
                        },
                        new
                        {
                            Id = new Guid("8aaa0d30-bdbe-4f2b-a6b8-f1a5466b2561"),
                            AllPermissions = false,
                            Description = "Can edit the Evaluation in administration",
                            Name = "Editor",
                            Permissions = new[] { 0, 1 }
                        },
                        new
                        {
                            Id = new Guid("4af74a62-596c-4767-a43a-b74aa8e48527"),
                            AllPermissions = false,
                            Description = "Can view the Evaluation in administration",
                            Name = "Viewer",
                            Permissions = new[] { 0 }
                        },
                        new
                        {
                            Id = new Guid("7c366199-f795-4a04-b360-e8705e77a053"),
                            AllPermissions = false,
                            Description = "Can observe all teams and advance moves for the Evaluation",
                            Name = "Facilitator",
                            Permissions = new[] { 4, 3 }
                        },
                        new
                        {
                            Id = new Guid("c1e1731c-d44a-4b6b-abc1-2e3626798304"),
                            AllPermissions = false,
                            Description = "Can advance moves for the Evaluation",
                            Name = "Advancer",
                            Permissions = new[] { 3 }
                        },
                        new
                        {
                            Id = new Guid("39aa296e-05ba-4fb0-8d74-c92cf3354c61"),
                            AllPermissions = false,
                            Description = "Has read only access to all teams in the Evaluation up to the current move",
                            Name = "Observer",
                            Permissions = new[] { 4 }
                        },
                        new
                        {
                            Id = new Guid("f870d8ee-7332-4f7f-8ee0-63bd07cfd7e6"),
                            AllPermissions = false,
                            Description = "Has read only access to the Evaluation up to the current move",
                            Name = "Member",
                            Permissions = new[] { 5 }
                        });
                });

            modelBuilder.Entity("Cite.Api.Data.Models.GroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("groups");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.GroupMembershipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique();

                    b.ToTable("group_memberships");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.MoveEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modified");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluation_id");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<int>("MoveNumber")
                        .HasColumnType("integer")
                        .HasColumnName("move_number");

                    b.Property<string>("SituationDescription")
                        .HasColumnType("text")
                        .HasColumnName("situation_description");

                    b.Property<DateTime>("SituationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("situation_time");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId", "MoveNumber")
                        .IsUnique();

                    b.ToTable("moves");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.PermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modified");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("read_only");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Value")
                        .IsUnique();

                    b.ToTable("permissions");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.ScoringCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CalculationEquation")
                        .HasColumnType("text")
                        .HasColumnName("calculation_equation");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modified");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsModifierRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_modifier_required");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<int>("MoveNumberFirstDisplay")
                        .HasColumnType("integer")
                        .HasColumnName("move_number_first_display");

                    b.Property<int>("MoveNumberLastDisplay")
                        .HasColumnType("integer")
                        .HasColumnName("move_number_last_display");

                    b.Property<Guid>("ScoringModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("scoring_model_id");

                    b.Property<int>("ScoringOptionSelection")
                        .HasColumnType("integer")
                        .HasColumnName("scoring_option_selection");

                    b.Property<double>("ScoringWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("scoring_weight");

                    b.HasKey("Id");

                    b.HasIndex("ScoringModelId");

                    b.ToTable("scoring_categories");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.ScoringModelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CalculationEquation")
                        .HasColumnType("text")
                        .HasColumnName("calculation_equation");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modified");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("DisplayCommentTextBoxes")
                        .HasColumnType("boolean")
                        .HasColumnName("display_comment_text_boxes");

                    b.Property<bool>("DisplayScoringModelByMoveNumber")
                        .HasColumnType("boolean")
                        .HasColumnName("display_scoring_model_by_move_number");

                    b.Property<Guid?>("EvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluation_id");

                    b.Property<bool>("HideScoresOnScoreSheet")
                        .HasColumnType("boolean")
                        .HasColumnName("hide_scores_on_score_sheet");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<int>("RightSideDisplay")
                        .HasColumnType("integer")
                        .HasColumnName("right_side_display");

                    b.Property<string>("RightSideEmbeddedUrl")
                        .HasColumnType("text")
                        .HasColumnName("right_side_embedded_url");

                    b.Property<string>("RightSideHtmlBlock")
                        .HasColumnType("text")
                        .HasColumnName("right_side_html_block");

                    b.Property<bool>("ShowPastSituationDescriptions")
                        .HasColumnType("boolean")
                        .HasColumnName("show_past_situation_descriptions");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<bool>("UseOfficialScore")
                        .HasColumnType("boolean")
                        .HasColumnName("use_official_score");

                    b.Property<bool>("UseSubmit")
                        .HasColumnType("boolean")
                        .HasColumnName("use_submit");

                    b.Property<bool>("UseTeamAverageScore")
                        .HasColumnType("boolean")
                        .HasColumnName("use_team_average_score");

                    b.Property<bool>("UseTeamScore")
                        .HasColumnType("boolean")
                        .HasColumnName("use_team_score");

                    b.Property<bool>("UseTypeAverageScore")
                        .HasColumnType("boolean")
                        .HasColumnName("use_type_average_score");

                    b.Property<bool>("UseUserScore")
                        .HasColumnType("boolean")
                        .HasColumnName("use_user_score");

                    b.HasKey("Id");

                    b.ToTable("scoring_models");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.ScoringModelMembershipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("f870d8ee-7332-4f7f-8ee0-63bd07cfd7e5"))
                        .HasColumnName("role_id");

                    b.Property<Guid>("ScoringModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("scoring_model_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("ScoringModelId", "UserId", "GroupId")
                        .IsUnique();

                    b.ToTable("scoring_model_memberships");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.ScoringModelRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("AllPermissions")
                        .HasColumnType("boolean")
                        .HasColumnName("all_permissions");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int[]>("Permissions")
                        .HasColumnType("integer[]")
                        .HasColumnName("permissions");

                    b.HasKey("Id");

                    b.ToTable("scoring_model_roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a3f26cd-9d99-4b98-b914-12931e786199"),
                            AllPermissions = true,
                            Description = "Can view, edit, and delete the ScoringModel",
                            Name = "Owner",
                            Permissions = new int[0]
                        },
                        new
                        {
                            Id = new Guid("f870d8ee-7332-4f7f-8ee0-63bd07cfd7e5"),
                            AllPermissions = false,
                            Description = "Can view and edit the ScoringModel",
                            Name = "Editor",
                            Permissions = new[] { 0, 1 }
                        },
                        new
                        {
                            Id = new Guid("39aa296e-05ba-4fb0-8d74-c92cf3354c60"),
                            AllPermissions = false,
                            Description = "Can view the ScoringModel",
                            Name = "Viewer",
                            Permissions = new[] { 0 }
                        });
                });

            modelBuilder.Entity("Cite.Api.Data.Models.ScoringOptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modified");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsModifier")
                        .HasColumnType("boolean")
                        .HasColumnName("is_modifier");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("ScoringCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("scoring_category_id");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ScoringCategoryId");

                    b.ToTable("scoring_options");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.SubmissionCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modified");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<Guid>("ScoringCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("scoring_category_id");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.HasKey("Id");

                    b.HasIndex("ScoringCategoryId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("submission_categories");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.SubmissionCommentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modified");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("SubmissionOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_option_id");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionOptionId");

                    b.ToTable("submission_comments");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.SubmissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modified");

                    b.Property<Guid?>("EvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluation_id");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<int>("MoveNumber")
                        .HasColumnType("integer")
                        .HasColumnName("move_number");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<Guid>("ScoringModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("scoring_model_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ScoringModelId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.HasIndex("EvaluationId", "UserId", "TeamId", "MoveNumber")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("EvaluationId", "UserId", "TeamId", "MoveNumber"), false);

                    b.ToTable("submissions");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.SubmissionOptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modified");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_selected");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("ScoringOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("scoring_option_id");

                    b.Property<Guid>("SubmissionCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_category_id");

                    b.HasKey("Id");

                    b.HasIndex("ScoringOptionId");

                    b.HasIndex("SubmissionCategoryId");

                    b.ToTable("submission_options");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.SystemRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("AllPermissions")
                        .HasColumnType("boolean")
                        .HasColumnName("all_permissions");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Immutable")
                        .HasColumnType("boolean")
                        .HasColumnName("immutable");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int[]>("Permissions")
                        .HasColumnType("integer[]")
                        .HasColumnName("permissions");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("system_roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f35e8fff-f996-4cba-b303-3ba515ad8d2f"),
                            AllPermissions = true,
                            Description = "Can perform all actions",
                            Immutable = true,
                            Name = "Administrator",
                            Permissions = new int[0]
                        },
                        new
                        {
                            Id = new Guid("d80b73c3-95d7-4468-8650-c62bbd082507"),
                            AllPermissions = false,
                            Description = "Can create and manage their own Evaluations and Scoring Models.",
                            Immutable = false,
                            Name = "Content Developer",
                            Permissions = new[] { 0, 4 }
                        },
                        new
                        {
                            Id = new Guid("1da3027e-725d-4753-9455-a836ed9bdb1e"),
                            AllPermissions = false,
                            Description = "Can View all Evaluations and Scoring Models, but cannot make any changes.",
                            Immutable = false,
                            Name = "Viewer",
                            Permissions = new[] { 1, 5, 10, 12, 14, 16 }
                        });
                });

            modelBuilder.Entity("Cite.Api.Data.Models.TeamEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modified");

                    b.Property<Guid?>("EvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluation_id");

                    b.Property<bool>("HideScoresheet")
                        .HasColumnType("boolean")
                        .HasColumnName("hide_scoresheet");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<Guid>("TeamTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_type_id");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("TeamTypeId");

                    b.ToTable("teams");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.TeamMembershipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique();

                    b.ToTable("team_memberships");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.TeamRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int[]>("Permissions")
                        .HasColumnType("integer[]")
                        .HasColumnName("permissions");

                    b.HasKey("Id");

                    b.ToTable("team_roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2cc11c1-9fd1-402b-9937-0f6ede1066c3"),
                            Description = "Can perform all actions for the Team",
                            Name = "Owner",
                            Permissions = new[] { 0, 1, 2, 3 }
                        },
                        new
                        {
                            Id = new Guid("1cfce79f-f344-4cb1-b33a-55de8dc1ccb3"),
                            Description = "Can contribute to and submit the answers for the Team",
                            Name = "Submitter",
                            Permissions = new[] { 0, 1, 2 }
                        },
                        new
                        {
                            Id = new Guid("c442cf49-e26e-45c5-be7c-00e710d2e055"),
                            Description = "Can contribute answers for the Team",
                            Name = "Contributor",
                            Permissions = new[] { 0, 1 }
                        },
                        new
                        {
                            Id = new Guid("b52ef031-65ee-4597-b768-b73480e6de67"),
                            Description = "Has read only access to the Team",
                            Name = "Member",
                            Permissions = new[] { 0 }
                        });
                });

            modelBuilder.Entity("Cite.Api.Data.Models.TeamTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modified");

                    b.Property<bool>("IsOfficialScoreContributor")
                        .HasColumnType("boolean")
                        .HasColumnName("is_official_score_contributor");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("ShowTeamTypeAverage")
                        .HasColumnType("boolean")
                        .HasColumnName("show_team_type_average");

                    b.HasKey("Id");

                    b.ToTable("team_types");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.TeamUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("CanIncrementMove")
                        .HasColumnType("boolean")
                        .HasColumnName("can_increment_move");

                    b.Property<bool>("CanManageTeam")
                        .HasColumnType("boolean")
                        .HasColumnName("can_manage_team");

                    b.Property<bool>("CanModify")
                        .HasColumnType("boolean")
                        .HasColumnName("can_modify");

                    b.Property<bool>("CanSubmit")
                        .HasColumnType("boolean")
                        .HasColumnName("can_submit");

                    b.Property<bool>("IsObserver")
                        .HasColumnType("boolean")
                        .HasColumnName("is_observer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId", "TeamId")
                        .IsUnique();

                    b.ToTable("team_users");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modified");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.UserPermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId", "PermissionId")
                        .IsUnique();

                    b.ToTable("user_permissions");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.ActionEntity", b =>
                {
                    b.HasOne("Cite.Api.Data.Models.EvaluationEntity", "Evaluation")
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cite.Api.Data.Models.TeamEntity", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.DutyEntity", b =>
                {
                    b.HasOne("Cite.Api.Data.Models.EvaluationEntity", "Evaluation")
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cite.Api.Data.Models.TeamEntity", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.DutyUserEntity", b =>
                {
                    b.HasOne("Cite.Api.Data.Models.DutyEntity", "Duty")
                        .WithMany("DutyUsers")
                        .HasForeignKey("DutyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cite.Api.Data.Models.UserEntity", "User")
                        .WithMany("DutyUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Duty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.EvaluationEntity", b =>
                {
                    b.HasOne("Cite.Api.Data.Models.ScoringModelEntity", "ScoringModel")
                        .WithMany()
                        .HasForeignKey("ScoringModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoringModel");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.EvaluationMembershipEntity", b =>
                {
                    b.HasOne("Cite.Api.Data.Models.EvaluationEntity", "Evaluation")
                        .WithMany("Memberships")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cite.Api.Data.Models.GroupEntity", "Group")
                        .WithMany("EvaluationMemberships")
                        .HasForeignKey("GroupId");

                    b.HasOne("Cite.Api.Data.Models.EvaluationRoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cite.Api.Data.Models.UserEntity", "User")
                        .WithMany("EvaluationMemberships")
                        .HasForeignKey("UserId");

                    b.Navigation("Evaluation");

                    b.Navigation("Group");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.GroupMembershipEntity", b =>
                {
                    b.HasOne("Cite.Api.Data.Models.GroupEntity", "Group")
                        .WithMany("Memberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cite.Api.Data.Models.UserEntity", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.MoveEntity", b =>
                {
                    b.HasOne("Cite.Api.Data.Models.EvaluationEntity", "Evaluation")
                        .WithMany("Moves")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.ScoringCategoryEntity", b =>
                {
                    b.HasOne("Cite.Api.Data.Models.ScoringModelEntity", "ScoringModel")
                        .WithMany("ScoringCategories")
                        .HasForeignKey("ScoringModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoringModel");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.ScoringModelMembershipEntity", b =>
                {
                    b.HasOne("Cite.Api.Data.Models.GroupEntity", "Group")
                        .WithMany("ScoringModelMemberships")
                        .HasForeignKey("GroupId");

                    b.HasOne("Cite.Api.Data.Models.ScoringModelRoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cite.Api.Data.Models.ScoringModelEntity", "ScoringModel")
                        .WithMany("Memberships")
                        .HasForeignKey("ScoringModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cite.Api.Data.Models.UserEntity", "User")
                        .WithMany("ScoringModelMemberships")
                        .HasForeignKey("UserId");

                    b.Navigation("Group");

                    b.Navigation("Role");

                    b.Navigation("ScoringModel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.ScoringOptionEntity", b =>
                {
                    b.HasOne("Cite.Api.Data.Models.ScoringCategoryEntity", "ScoringCategory")
                        .WithMany("ScoringOptions")
                        .HasForeignKey("ScoringCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoringCategory");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.SubmissionCategoryEntity", b =>
                {
                    b.HasOne("Cite.Api.Data.Models.ScoringCategoryEntity", "ScoringCategory")
                        .WithMany()
                        .HasForeignKey("ScoringCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cite.Api.Data.Models.SubmissionEntity", "Submission")
                        .WithMany("SubmissionCategories")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoringCategory");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.SubmissionCommentEntity", b =>
                {
                    b.HasOne("Cite.Api.Data.Models.SubmissionOptionEntity", "SubmissionOption")
                        .WithMany("SubmissionComments")
                        .HasForeignKey("SubmissionOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmissionOption");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.SubmissionEntity", b =>
                {
                    b.HasOne("Cite.Api.Data.Models.EvaluationEntity", "Evaluation")
                        .WithMany("Submissions")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cite.Api.Data.Models.ScoringModelEntity", "ScoringModel")
                        .WithMany()
                        .HasForeignKey("ScoringModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cite.Api.Data.Models.TeamEntity", "Team")
                        .WithMany("Submissions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cite.Api.Data.Models.UserEntity", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Evaluation");

                    b.Navigation("ScoringModel");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.SubmissionOptionEntity", b =>
                {
                    b.HasOne("Cite.Api.Data.Models.ScoringOptionEntity", "ScoringOption")
                        .WithMany()
                        .HasForeignKey("ScoringOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cite.Api.Data.Models.SubmissionCategoryEntity", "SubmissionCategory")
                        .WithMany("SubmissionOptions")
                        .HasForeignKey("SubmissionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoringOption");

                    b.Navigation("SubmissionCategory");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.TeamEntity", b =>
                {
                    b.HasOne("Cite.Api.Data.Models.EvaluationEntity", "Evaluation")
                        .WithMany("Teams")
                        .HasForeignKey("EvaluationId");

                    b.HasOne("Cite.Api.Data.Models.TeamTypeEntity", "TeamType")
                        .WithMany()
                        .HasForeignKey("TeamTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("TeamType");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.TeamMembershipEntity", b =>
                {
                    b.HasOne("Cite.Api.Data.Models.TeamRoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("Cite.Api.Data.Models.TeamEntity", "Team")
                        .WithMany("Memberships")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cite.Api.Data.Models.UserEntity", "User")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.TeamUserEntity", b =>
                {
                    b.HasOne("Cite.Api.Data.Models.TeamEntity", "Team")
                        .WithMany("TeamUsers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cite.Api.Data.Models.UserEntity", "User")
                        .WithMany("TeamUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.UserEntity", b =>
                {
                    b.HasOne("Cite.Api.Data.Models.SystemRoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.UserPermissionEntity", b =>
                {
                    b.HasOne("Cite.Api.Data.Models.PermissionEntity", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cite.Api.Data.Models.UserEntity", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.DutyEntity", b =>
                {
                    b.Navigation("DutyUsers");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.EvaluationEntity", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Moves");

                    b.Navigation("Submissions");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.GroupEntity", b =>
                {
                    b.Navigation("EvaluationMemberships");

                    b.Navigation("Memberships");

                    b.Navigation("ScoringModelMemberships");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.PermissionEntity", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.ScoringCategoryEntity", b =>
                {
                    b.Navigation("ScoringOptions");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.ScoringModelEntity", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("ScoringCategories");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.SubmissionCategoryEntity", b =>
                {
                    b.Navigation("SubmissionOptions");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.SubmissionEntity", b =>
                {
                    b.Navigation("SubmissionCategories");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.SubmissionOptionEntity", b =>
                {
                    b.Navigation("SubmissionComments");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.TeamEntity", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Submissions");

                    b.Navigation("TeamUsers");
                });

            modelBuilder.Entity("Cite.Api.Data.Models.UserEntity", b =>
                {
                    b.Navigation("DutyUsers");

                    b.Navigation("EvaluationMemberships");

                    b.Navigation("GroupMemberships");

                    b.Navigation("ScoringModelMemberships");

                    b.Navigation("Submissions");

                    b.Navigation("TeamMemberships");

                    b.Navigation("TeamUsers");

                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
