# docker-compose up -d

version: '3.2'
networks:
  cite-network:
    driver: bridge
services:
  postgres:
    image: postgres
    container_name:  cite-postgres
    environment:
      POSTGRES_DB: cite_api
      POSTGRES_USER: cite
      POSTGRES_PASSWORD: Tartans@@1
    volumes:
      - ./_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cite"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - cite-network
    restart: always

  cite-api:
    image: cite/api
    container_name: cite-api
    depends_on:
      - postgres
    ports:
      - "4720:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - cite-network
    restart: always
